### ISSUE TITLE
let's go for httplug

### ISSUE THREAD

**Issue by krichprollsch** [Calendart/GoogleAdapter#18]
As discussed into #17 using [httplug](https://github.com/php-http/httplug) will remove the pain of maintain guzzle dependency up to date.

Moreover it allows the final user to choose the best http client for its needs.

But adding httplug introduces a BC break...

**Comment by Taluu** [comment]
As I already told you, I'm okay for a BC break on next major (this is what semantic versionning is for afterall), but IMO I want to do all the bc breaks we have to do before releasing a 2.0 (I don't want to have a 3.0 then a 4.0 etc, as guzzle does it actually :-*)

**Comment by krichprollsch** [comment]
So it will be the first stone for the next release.
